### ISSUE TITLE
order of the tools

### ISSUE THREAD

**Issue by avilella** [veidenberg/pline#1]
Hi, I've tried pline today and I find it a very useful way to enable wet-lab scientists in using tools with a CLI.

Is there a way of reordering the list of tools based on a specific "prefix" or "category"?

I see the plugin for pagan has prefix "--" and category "aligners", but in my list, Codeml appears first, with a prefix "" and no category.

What's the best way to group and then sort based on the preferred grouping? Thanks in advance.

**Comment by veidenberg** [comment]
Hi @avilella, sorry for the long delay (I didn't have issue notifications enabled).
While the placement of the inputs/input groups for each tool interface reflect its order in the JSON, each tool (or tools pipeline) is an independent plugin that lives in the `Pline.plugins` object. How/when to show each tool depends on the webpage container integrating Pline (e.g. by utilizing `Pline.registerPlugin()`). The [demo site](http://wasabiapp.org/pline-demo/), for example, uses the built-in pop-up menu that lists the tools alphabetically while [Wasabi](http://was.bi) uses the `category` property to divide the tools into submenus. The prefix property defines the default prefix for the command-line parameters for the tool.
So to reorder/group, you can change the ordering in the [pop-up menu function](https://github.com/veidenberg/pline/blob/bef39ce021cf826292337ad4753c99dfff05ff2b/pline.js#L271) (when using the web page container included in the repo) or reorder the tools from Pline.plugins to another array for drawing (see an [example in Wasabi repository](https://github.com/veidenberg/wasabi/blob/8a85f46c8480e5a477390b9db6886a57ce5c1290/javascript/script.js#L4634)).

**Comment by avilella** [comment]
Thanks, will try.

**Comment by avilella** [comment]
Coming back for this: we've now accumulated about 40 different plugins, people find them very useful, and it is more cumbersome than before not to have the plugins sorted. I looked at it, and it turns out that `makeMenu` never goes through the sort statement below:
https://github.com/veidenberg/pline/blob/bef39ce021cf826292337ad4753c99dfff05ff2b/pline.js#L271

Changing the text: wheel + plugin title statement does nothing.
```
        //make a pop-up menu                                                                                                                                                                                                                
        //btn=menu launcher DOM element; items=array[{title:str,click:func}]; arr=menu pointer direction ('top'|'bottom')                                                                                                                   
        makeMenu: function(btn, items, arr){
                if(!arr) arr = 'top';
                if(!Array.isArray(items)){
                        items = [];
                        var plugins = Object.keys(Pline.plugins).sort();
                        plugins.forEach( function(pname){ //default menu: the plugins list                                                                                                                                                  
                                var plugin = Pline.plugins[pname];
                                if(plugin.duplicate) return true;
                                items.push({
                                        // text: '⚙  '+plugin.title,                                                                                                                                                                        
                                        text: '--- '+plugin.title,
                                        title: 'Add '+plugin.title+' to the pipeline',
                                        click: function(){ plugin.draw(); }
                                });
                        });
                }
```

But if I comment out the `                if(!Array.isArray(items)){` statement, then it does sort alphabetically!!
I'll leave it as it is for now, suggest a pull request.
